@startuml actions
title Описание GitHub Actions

[*] --> test : Запускается при создании PR и при обновлениях в PR

test : - Линтинг Ruff
test : - Проверки Mypy
test : - Запуск Pytest
test : - Сборка и публикация образа (с тэгом test)
test : - Тестирование контейнера
test : - Перетегирование образа как tested
test : - Публикация протестированного образа в GHCR
test : - Удаление тэга test из GHCR

test --> release : Если PR слит в main или запущен вручную

release : - Перетегировать образ как latest
release : - Публикация в GHCR и Docker Hub
release : - Удаление тэга tested из GHCR

release --> [*]

note right of test
  Если изменения не в путях:
  - docs/**
  - nginx/**
  - .vscode/**
end note

note right of release
  Если изменения не в путях:
  - docs/**
  - nginx/**
  - .vscode/**
end note

@enduml
