# Generated by Django 6.0.2 on 2026-09-18 19:48

from django.db import migrations, models


def create_about_page(apps, schema_editor) -> None:
    """Создает пустую запись страницы, если она отсутствует."""
    AboutPage = apps.get_model("about", "AboutPage")
    AboutPage.objects.get_or_create(pk=1)


def delete_about_page(apps, schema_editor) -> None:
    """Удаляет запись страницы при откате миграции."""
    AboutPage = apps.get_model("about", "AboutPage")
    AboutPage.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(blank=True, verbose_name="Содержимое страницы")),
            ],
            options={
                "verbose_name": "Страница Обо мне",
                "verbose_name_plural": "Страница Обо мне",
            },
        ),
        migrations.RunPython(create_about_page, delete_about_page),
    ]
