# Generated by Django 6.0.2 on 2026-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(blank=True, verbose_name="Содержимое страницы")),
            ],
            options={
                "verbose_name": "Страница Обо мне",
                "verbose_name_plural": "Страница Обо мне",
            },
        ),
    ]
