# Generated by Django 6.0.2 on 2026-09-19 17:15

from django.db import migrations, models


def create_about(apps, schema_editor) -> None:
    """Создает пустую запись данных, если она отсутствует."""
    About = apps.get_model("about", "About")
    About.objects.get_or_create(pk=1)


def delete_about(apps, schema_editor) -> None:
    """Удаляет запись данных при откате миграции."""
    About = apps.get_model("about", "About")
    About.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(blank=True, verbose_name="Содержимое")),
            ],
            options={
                "verbose_name": "Обо мне",
                "verbose_name_plural": "Обо мне",
            },
        ),
        migrations.RunPython(create_about, delete_about),
    ]
