version: '3'

tasks:
  commit:
    desc: Зафиксировать и отправить изменения в удаленный репозиторий
    summary: |
      Команда вызывает bash-скрипт для подготовки, выполнения и отправки коммита в удаленный репозиторий git.
      При вызове команды можно передать сообщение для коммита через аргумент командной строки.
      Пример использования с аргументом: task commit -- "Commit message"
      Пример использования без аргумента: task commit
    cmds:
      - bash ./tools/commit.sh {{.CLI_ARGS}}
