version: '3'

dotenv: ['.env']

tasks:
  commit:
    desc: Зафиксировать и отправить изменения в удаленный репозиторий
    summary: |
      Команда вызывает Bash-скрипт для подготовки, выполнения и отправки коммита в удаленный репозиторий Git.
      При вызове команды можно передать сообщение для коммита через аргумент командной строки.
      Пример использования с аргументом: `task commit -- "Commit message"`
      Пример использования без аргумента: `task commit`
    cmds:
      - bash ./tools/commit.sh {{.CLI_ARGS}}

  checkout:
    desc: Переключиться на ветку из удаленного репозитория
    summary: |
      Команда вызывает Bash-скрипт для создания локальной отслеживающей ветки для удалённой ветки.
      При вызове команды можно передать имя ветки через аргумент командной строки.
      Если имя ветки не передано, то будет запрошено у пользователя.
      Пример использования с аргументом: `task checkout -- "branch-name"`
      Пример использования без аргумента: `task checkout`
    cmds:
      - bash ./tools/checkout.sh {{.CLI_ARGS}}

  runserver:
    desc: Запустить сервер приложения
    summary: |
      Запускает сервер приложения Django. Альтернатива команде `python manage.py runserver`.
      Интерпретатор Python запускается через Poetry из виртуального окружения проекта.
      Перед запуском сервера применяются миграции базы данных и собираются статические файлы.
      Сервер PostgreSQL запускается в контейнере через Docker Compose.
    preconditions:
      - test -f compose.yaml
      - test -f .env
    env:
      POSTGRES_HOST: localhost
    cmds:
      - defer: docker-compose down
      - docker-compose up -d postgres
      - docker-compose ps
      - poetry run python ./personal_website/manage.py migrate
      - poetry run python ./personal_website/manage.py collectstatic --noinput
      - poetry run python ./personal_website/manage.py runserver

  migrate:
    desc: Подготовить и выполнить миграции, экспортировать новые диаграммы моделей
    summary: |
      Проверить изменения во всех моделях, сгенерировать миграции,
      применить миграции к базе данных и экспортировать актуальные диаграммы моделей.
    preconditions:
      - test -f compose.yaml
      - test -f .env
    env:
      POSTGRES_HOST: localhost
    cmds:
      - defer: docker-compose down
      - docker-compose up -d postgres
      - docker-compose ps
      - poetry run python ./personal_website/manage.py makemigrations
      - poetry run python ./personal_website/manage.py migrate
      - task: graph-models

  test:
    desc: Выполнить тесты
    summary: |
      Команда выполянет тесты проекта Python/Django через Pytest с формированием отчета Coverage в формате HTML
      и тесты вспомогательных модулей Node.js. Интерпретатор Python запускается через Poetry из виртуального
      окружения проекта. Сервер базы данных PostgreSQL запускается в контейнере через Docker Compose.
    preconditions:
      - test -f compose.yaml
      - test -f pyproject.toml
      - test -f .env
    env:
      POSTGRES_HOST: localhost
      MINIO_SERVER_URL: http://127.0.0.1:9000
      MINIO_BROWSER_REDIRECT_URL: http://127.0.0.1:9001
    cmds:
      - defer: docker-compose down
      - docker-compose up -d postgres
      - docker-compose ps
      - npm test
      - poetry run pytest {{.CLI_ARGS}}

  test-container:
    desc: Выполнить тесты в контейнере
    summary: |
      Команда выполняет в контейнере тесты проекта Python/Django через Pytest и тесты вспомогательных модулей Node.js.
      Сервер базы данных PostgreSQL запускается в контейнере через Docker Compose.
    preconditions:
      - test -f compose.yaml
      - test -f pyproject.toml
      - test -f .env
    env:
      POSTGRES_HOST: postgres
    cmds:
      - defer: docker-compose down
      - docker-compose up -d website postgres
      - docker-compose ps
      - docker-compose exec website npm test
      - docker-compose exec website poetry run pytest {{.CLI_ARGS}}

  test-integration:
    desc: Выполнить интеграционные тесты
    summary: |
      Команда выполняет только интеграционные тесты из папки tests в корневом каталоге
      проекта через Pytest. Интерпретатор Python запускается через Poetry из виртуального
      окружения проекта. Сервисы поднимаются в контейнерах Docker через Compose.
    preconditions:
      - test -f compose.yaml
      - test -f pyproject.toml
      - test -f .env
    env:
      POSTGRES_HOST: postgres
      MINIO_SERVER_URL: http://127.0.0.1:9000
      MINIO_BROWSER_REDIRECT_URL: http://127.0.0.1:9001
    cmds:
      - defer: docker-compose down
      - docker-compose up -d postgres nginx minio
      - docker-compose ps
      - poetry run pytest ./tests {{.CLI_ARGS}}

  ruff:
    desc: Выполнить статический анализ кода при помощи утилиты Ruff
    summary: Команда запускает проверки Ruff с автоматически исправлением ошибок
    preconditions:
      - test -f pyproject.toml
    cmds:
      - poetry run ruff check --fix

  mypy:
    desc: Выполнить статический анализ кода при помощи утилиты Mypy
    summary: Команда запускает проверки типов Mypy
    preconditions:
      - test -f pyproject.toml
    cmds:
      - poetry run mypy .

  check:
    desc: Выполнить статический анализ кода и проверки Django
    summary: Команда запускает проверки Ruff, Mypy и Django
    preconditions:
      - test -f pyproject.toml
    cmds:
      - task: ruff
      - task: mypy
      - poetry run python personal_website/manage.py check

  install:
    desc: Установить зависимости Python и Node.js
    summary: |
      Выполняет установку зависимостей Python при помощи Poetry и зависимостей Node.js при помощи npm.
      Списки зависимостей считываются из файлов pyproject.toml и package.json.
    preconditions:
      - test -f pyproject.toml
      - test -f package.json
    cmds:
      - poetry install
      - npm install

  update:
    desc: Обновить версии зависимостей Python и Node.js
    summary: |
      Обновляет до последних допустимых версий пакеты Python
      при помощи плагина poetry-plugin-up и
      зависимости Node.js при помощи npm.
    preconditions:
        - test -f pyproject.toml
        - test -f package.json
    cmds:
      - poetry up --latest
      - npm update

  build:
    desc: Выполнить сборку образов контейнеров
    summary: |
      Выполняет сборку контейнеров Docker для сервисов приложения и Nginx, определенных в файле compose.yaml.
      Инструкции по сборке образов определены в файлах Dockerfile для каждого сервиса.
    preconditions:
      - test -f compose.yaml
      - test -f .env
    cmds:
      - docker-compose build

  up-detached:
    desc: Запустить контейнеры в фоновом режиме
    summary: |
      Запускает контейнеры Docker сервисов, определенных в файле Compose, в фоновом режиме (detached).
    preconditions:
      - test -f compose.yaml
      - test -f .env
    cmds:
      - docker-compose up -d website postgres minio
      - docker-compose ps

  restart:
    desc: Перезапускает контейнеры сервисов
    summary: |
      Пересоздает и перезапускает контейнеры Docker сервисов, определенных в файле Compose,
      в фоновом режиме (detached). Полезно в случае изменений переменных окружения.
    preconditions:
      - test -f compose.yaml
      - test -f .env
    cmds:
      - docker-compose up --detach --force-recreate
      - docker-compose ps

  watch:
    desc: Запустить контейнеры в фоновом режиме и отслеживать изменения кода
    summary: |
      Запускает контейнеры Docker в фоновом режиме и пересоздает контейнеры в случае изменений при помощи Compose Watch.
    preconditions:
      - test -f compose.yaml
      - test -f .env
    env:
      POSTGRES_HOST: postgres
      MINIO_SERVER_URL: http://minio:9000
      MINIO_BROWSER_REDIRECT_URL: http://minio:9001
    cmds:
      - docker-compose up -d
      - docker-compose ps
      - docker-compose watch

  down:
    desc: Остановить контейнеры и удалить остановленные контейнеры, тома и сети
    summary: |
      Аналог команды `docker-compose down`: останавливает запущенные контейнеры, удаляет контейнеры, тома и сети.
    preconditions:
      - test -f compose.yaml
    cmds:
      - docker-compose down --remove-orphans --volumes

  postgres:
    desc: Запустить контейнер PostgreSQL
    summary: |
      Запускает контейнер сервиса PostgreSQL, определенного в файле Compose, в фоновом режиме (detached).
    preconditions:
      - test -f compose.yaml
      - test -f .env
    cmds:
      - docker-compose up -d postgres
      - docker-compose ps

  minio-alias:
    desc: Создать алиас для сервера MinIO
    summary: |
      Создает алиас сервера S3 для клиента MinIO (mc). Значения считываются из переменных окружения.
    preconditions:
      - test -f compose.yaml
      - test -f .env
    cmds:
      - defer: docker-compose down
      - docker-compose up -d minio
      - docker-compose ps
      - mc alias set ${MINIO_ALIAS} ${MINIO_SERVER_URL} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
      - mc admin info ${MINIO_ALIAS}

  delete-branches:
    desc: Удалить все ветки, кроме основной
    summary: |
      Выполняет команду `git branch -D` для всех веток, кроме main и текущей.
    cmds:
      - git branch | grep -v "main" | xargs git branch -D

  graph-models:
    desc: Экспортировать диаграммы моделей проекта
    summary: |
      Выполняет команду grap_models из пакета django-extensions для всего проекта,
      приложений проекта в совокупности и каждого приложения в отдельности.
    cmds:
      - bash ./tools/graphmodels.sh

  check-migrations:
    desc: Проверить проект на отсутствующие миграции
    summary: |
      Проверить, что отсутствуют изменения в моделях, для которых не подготовлено миграций.
      Выполняет команду makemigrations с аргументами --dry-run и --check.
      Возвращает не нулевой код ответа в случае отсутствия миграций.
    preconditions:
      - test -f pyproject.toml
      - test -f compose.yaml
      - test -f .env
    env:
      POSTGRES_HOST: localhost
    cmds:
      - defer: docker-compose down
      - docker-compose up -d postgres
      - docker-compose ps
      - poetry run python personal_website/manage.py makemigrations --dry-run --check

  clean-cache:
    desc: Удалить файлы кэша
    summary: |
      Удаляет все папки __pycache__ и файлы c расширением .pyc из дерева каталогов проекта.
    cmds:
      - find . | grep -E "(/__pycache__$|\.pyc$|\.pyo$)" | xargs rm -rf
