# Generated by Django 4.2.4 on 2023-09-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="cover",
            field=models.OneToOneField(
                blank=True,
                help_text="Обложка альбома",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="gallery.photo",
                verbose_name="Обложка",
            ),
        ),
    ]
