# Generated by hand

import io
from datetime import datetime
from datetime import timezone as dt_timezone

from django.db import migrations, models
from django.db.models.fields.files import FieldFile
from django.utils.timezone import is_aware, make_naive
from PIL import Image as pImage

# EXIF теги для чтения данных
TAGS = {
    36864: "ExifVersion",
    36867: "DateTimeOriginal",
    36868: "DateTimeDigitized",
    37121: "ComponentsConfiguration",
    37377: "ShutterSpeedValue",
    37378: "ApertureValue",
    37379: "BrightnessValue",
    37380: "ExposureBiasValue",
    37381: "MaxApertureValue",
    37382: "SubjectDistance",
    37383: "MeteringMode",
    37384: "LightSource",
    37385: "Flash",
    37386: "FocalLength",
    37520: "SubsecTime",
    37510: "SubsecTimeOriginal",
    37521: "SubsecTimeDigitized",
    41987: "CustomRendered",
    41988: "ExposureMode",
    41989: "WhiteBalance",
    41990: "DigitalZoomRatio",
    41991: "FocalLengthIn35mmFilm",
    41992: "SceneCaptureType",
    41993: "GainControl",
    41994: "Contrast",
    41995: "Saturation",
    41996: "Sharpness",
    41997: "SubjectDistanceRange",
    33434: "ExposureTime",
    33437: "FNumber",
    34855: "ISOSpeedRatings",
    "Make": "Make",
    "Model": "Model",
}


def get_exif_from_image(image_field: FieldFile) -> dict:
    """Получить EXIF данные из файла изображения.

    Args:
        image_field: Поле изображения модели Photo.

    Returns:
        Словарь с EXIF данными.
    """
    exif_data = {}
    if image_field.name and image_field.storage.exists(image_field.name):
        with image_field.open("rb") as f:
            img_bytes = f.read()
        with pImage.open(io.BytesIO(img_bytes)) as img:
            if hasattr(img, "_getexif"):
                info = img._getexif()  # noqa: SLF001
                if not info:
                    return {}
                for tag, value in info.items():
                    decoded = TAGS.get(tag, tag)
                    exif_data[decoded] = value
    return exif_data


def populate_taken_at(apps, schema_editor):
    """Заполнить поле taken_at для существующих фотографий.

    Извлекает дату съемки из EXIF данных изображения.
    Если EXIF отсутствует или не содержит даты, использует дату модификации файла.
    """
    Photo = apps.get_model("gallery", "Photo")

    for photo in Photo.objects.all():
        # Попытка получить EXIF данные напрямую из файла
        exif_data = get_exif_from_image(photo.image)

        # Получить дату из EXIF
        original_exif = exif_data.get("DateTimeOriginal")

        if original_exif:
            try:
                taken_at = datetime.strptime(original_exif, "%Y:%m:%d %H:%M:%S")  # noqa: DTZ007
            except ValueError:
                # Если не удалось распарсить дату из EXIF, используем дату модификации файла
                if photo.image.name:
                    storage = photo.image.storage
                    modified_time = storage.get_modified_time(photo.image.name)
                    taken_at = make_naive(modified_time) if is_aware(modified_time) else modified_time
                else:
                    taken_at = datetime.now(dt_timezone.utc)
        # Если EXIF не содержит даты, используем дату модификации файла
        elif photo.image.name:
            storage = photo.image.storage
            modified_time = storage.get_modified_time(photo.image.name)
            taken_at = make_naive(modified_time) if is_aware(modified_time) else modified_time
        else:
            taken_at = datetime.now(dt_timezone.utc)

        photo.taken_at = taken_at
        photo.save(update_fields=["taken_at"])


def reverse_populate_taken_at(apps, schema_editor):
    """Откат миграции данных - очистить поле taken_at."""
    Photo = apps.get_model("gallery", "Photo")
    Photo.objects.all().update(taken_at=None)


class Migration(migrations.Migration):
    """Миграция для добавления поля taken_at."""

    dependencies = [
        ("gallery", "0008_photo_album_related_name"),
    ]

    operations = [
        # Шаг 1: Добавить поле с null=True для миграции данных
        migrations.AddField(
            model_name="photo",
            name="taken_at",
            field=models.DateTimeField(
                verbose_name="Создана",
                null=True,
                blank=True,
                help_text="Дата и время съемки фотографии",
            ),
        ),
        # Шаг 2: Заполнить поле данными
        migrations.RunPython(
            populate_taken_at,
            reverse_populate_taken_at,
        ),
        # Шаг 3: Изменить поле на null=False, blank=False
        migrations.AlterField(
            model_name="photo",
            name="taken_at",
            field=models.DateTimeField(
                verbose_name="Создана",
                null=False,
                blank=False,
                help_text="Дата и время съемки фотографии",
            ),
        ),
    ]
