# Generated by hand

import contextlib
import io
from datetime import datetime
from datetime import timezone as dt_timezone

from django.db import migrations, models
from django.db.models.fields.files import FieldFile
from django.utils.timezone import is_aware, make_naive
from PIL import Image as pImage
from PIL.ExifTags import TAGS


def get_exif_from_image(image_field: FieldFile) -> dict:
    """Получить EXIF данные из файла изображения.

    Args:
        image_field: Поле изображения модели Photo.

    Returns:
        Словарь с EXIF данными.
    """
    exif_data = {}
    if image_field.name and image_field.storage.exists(image_field.name):
        with image_field.open("rb") as f:
            img_bytes = f.read()
        with pImage.open(io.BytesIO(img_bytes)) as img:
            if hasattr(img, "_getexif"):
                info = img._getexif()  # noqa: SLF001
                if not info:
                    return {}
                for tag, value in info.items():
                    decoded = TAGS.get(tag, tag)
                    exif_data[decoded] = value
    return exif_data


def get_fallback_datetime(image_field: FieldFile) -> datetime:
    """Получить резервную дату из модификации файла или текущее время.

    Args:
        image_field: Поле изображения модели Photo.

    Returns:
        Дата и время для использования в качестве taken_at.
    """
    if image_field.name:
        try:
            storage = image_field.storage
            modified_time = storage.get_modified_time(image_field.name)
            return make_naive(modified_time) if is_aware(modified_time) else modified_time
        except (FileNotFoundError, OSError):
            pass
    return datetime.now(dt_timezone.utc)


def populate_taken_at(apps, schema_editor):
    """Заполнить поле taken_at для существующих фотографий.

    Извлекает дату съемки из EXIF данных изображения.
    Если EXIF отсутствует или не содержит даты, использует дату модификации файла.
    """
    Photo = apps.get_model("gallery", "Photo")

    for photo in Photo.objects.all():
        exif_data = get_exif_from_image(photo.image)
        original_exif = exif_data.get("DateTimeOriginal")

        taken_at = None
        if original_exif:
            with contextlib.suppress(ValueError):
                taken_at = datetime.strptime(original_exif, "%Y:%m:%d %H:%M:%S")  # noqa: DTZ007

        if taken_at is None:
            taken_at = get_fallback_datetime(photo.image)

        photo.taken_at = taken_at
        photo.save(update_fields=["taken_at"])


def reverse_populate_taken_at(apps, schema_editor):
    """Откат миграции данных - очистить поле taken_at."""
    Photo = apps.get_model("gallery", "Photo")
    Photo.objects.all().update(taken_at=None)


class Migration(migrations.Migration):
    """Миграция для добавления поля taken_at."""

    dependencies = [
        ("gallery", "0008_photo_album_related_name"),
    ]

    operations = [
        # Шаг 1: Добавить поле с null=True для миграции данных
        migrations.AddField(
            model_name="photo",
            name="taken_at",
            field=models.DateTimeField(
                verbose_name="Создана",
                null=True,
                blank=True,
                help_text="Дата и время съемки фотографии",
            ),
        ),
        # Шаг 2: Заполнить поле данными
        migrations.RunPython(
            populate_taken_at,
            reverse_populate_taken_at,
        ),
        # Шаг 3: Изменить поле на null=False, blank=False
        migrations.AlterField(
            model_name="photo",
            name="taken_at",
            field=models.DateTimeField(
                verbose_name="Создана",
                null=False,
                blank=False,
                help_text="Дата и время съемки фотографии",
            ),
        ),
    ]
