# Generated by hand

from django.db import migrations, models

from gallery.utils import compute_datetime_taken


def populate_taken_at(apps, schema_editor):
    """Заполнить поле taken_at для существующих фотографий."""
    Photo = apps.get_model("gallery", "Photo")

    for photo in Photo.objects.all():
        photo.taken_at = compute_datetime_taken(photo)
        photo.save(update_fields=["taken_at"])


def reverse_populate_taken_at(apps, schema_editor):
    """Откат миграции данных - очистить поле taken_at."""
    Photo = apps.get_model("gallery", "Photo")
    Photo.objects.all().update(taken_at=None)


class Migration(migrations.Migration):
    """Миграция для добавления поля taken_at."""

    dependencies = [
        ("gallery", "0008_photo_album_related_name"),
    ]

    operations = [
        # Шаг 1: Добавить поле с null=True для миграции данных
        migrations.AddField(
            model_name="photo",
            name="taken_at",
            field=models.DateTimeField(
                verbose_name="Создана",
                null=True,
                blank=True,
                help_text="Дата и время съемки фотографии",
            ),
        ),
        # Шаг 2: Заполнить поле данными
        migrations.RunPython(
            populate_taken_at,
            reverse_populate_taken_at,
        ),
        # Шаг 3: Изменить поле на null=False, blank=False
        migrations.AlterField(
            model_name="photo",
            name="taken_at",
            field=models.DateTimeField(
                verbose_name="Создана",
                null=False,
                blank=False,
                help_text="Дата и время съемки фотографии",
            ),
        ),
    ]
