# Generated by Django 6.0.2 on 2026-07-25 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0009_photo_taken_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ("order", "-created_at"), "verbose_name": "Альбом", "verbose_name_plural": "Альбомы"},
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ("-taken_at",), "verbose_name": "Фотография", "verbose_name_plural": "Фотографии"},
        ),
    ]
