# Generated by Django 6.0.2 on 2026-07-25 22:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0010_alter_album_options_alter_photo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ("-order", "-created_at"), "verbose_name": "Альбом", "verbose_name_plural": "Альбомы"},
        ),
    ]
