# Generated by Django 6.0.2 on 2026-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0011_alter_album_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="exif",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="EXIF данные изображения",
                null=True,
                verbose_name="EXIF данные",
            ),
        ),
    ]
