# Generated by Django 4.0 on 2022-04-14 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('published', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('modified', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='blog/articles/', verbose_name='Картинка')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='blog/categories/', verbose_name='Картинка')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Серия')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='blog/series/', verbose_name='Картинка')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name_plural': 'Серии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Тема')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='blog/topics/', verbose_name='Картинка')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
                'ordering': ['posted'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ManyToManyField(blank=True, to='blog.Series'),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(blank=True, to='blog.Topic'),
        ),
    ]
