# Generated by Django 4.1.3 on 2022-12-07 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="category",
            new_name="categories",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="topic",
            new_name="topics",
        ),
    ]
