# Generated by Django 4.1.3 on 2022-12-07 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_category_article_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения"),
        ),
        migrations.AlterField(
            model_name="article",
            name="published",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата публикации"),
        ),
    ]
