# Generated by Django 4.2.4 on 2023-09-21 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_article_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-published_at"], "verbose_name_plural": "Статьи"},
        ),
        migrations.RenameField(
            model_name="article",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="published",
            new_name="published_at",
        ),
    ]
