# Generated by Django 5.0.1 on 2024-10-13 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ("-published_at",), "verbose_name_plural": "Статьи"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("posted",), "verbose_name_plural": "Комментарии"},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"ordering": ("name",), "verbose_name_plural": "Серии"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ("name",), "verbose_name_plural": "Темы"},
        ),
    ]
