# Generated by Django 4.1.3 on 2022-12-11 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_article_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="published",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Дата публикации",
            ),
        ),
    ]
