# Generated by Django 3.1.4 on 2020-12-23 18:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тема')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', tinymce.models.HTMLField(verbose_name='Содержание')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('theme', models.ManyToManyField(blank=True, to='blog.Theme')),
            ],
        ),
    ]
