# Generated by Django 3.1.4 on 2020-12-28 16:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200, verbose_name='Серия')),
                ('series_slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'ordering': ['series_name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200, verbose_name='Тема')),
                ('topic_slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'ordering': ['topic_name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('article_content', tinymce.models.HTMLField(verbose_name='Содержание')),
                ('article_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('article_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('article_slug', models.SlugField(verbose_name='Ссылка')),
                ('article_series', models.ManyToManyField(blank=True, to='blog.Series')),
                ('article_theme', models.ManyToManyField(to='blog.Topic')),
            ],
            options={
                'ordering': ['-article_published'],
            },
        ),
    ]
