# Generated by Django 3.1.4 on 2020-12-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тема')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('article_content', models.TextField(verbose_name='Содержание')),
                ('article_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('article_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('article_slug', models.SlugField(verbose_name='Ссылка')),
                ('article_theme', models.ManyToManyField(to='blog.Theme')),
            ],
            options={
                'ordering': ['-article_published'],
            },
        ),
    ]
