# Generated by Django 3.1.4 on 2021-01-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-article_published'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['series_name'], 'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['topic_name'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_theme',
        ),
        migrations.AddField(
            model_name='article',
            name='article_topic',
            field=models.ManyToManyField(blank=True, to='blog.Topic'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_slug',
            field=models.SlugField(unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_slug',
            field=models.SlugField(unique=True, verbose_name='Ссылка'),
        ),
    ]
