# Generated by Django 3.1.4 on 2020-12-24 18:03

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='document',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Изображение'),
        ),
    ]
