# Generated by Django 3.1.4 on 2020-12-26 15:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=tinymce.models.HTMLField(verbose_name='Содержание'),
        ),
    ]
