# Generated by Django 3.1.4 on 2020-12-20 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='BlogPost_content',
            field=tinymce.models.HTMLField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='BlogPost_published',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 15, 19, 10, 89028, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
