# Generated by Django 3.1.4 on 2020-12-20 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201220_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='BlogPost_published',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 15, 19, 29, 566875, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
