# Generated by Django 3.1.4 on 2021-01-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210104_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_visible',
            field=models.BooleanField(default=True, verbose_name='Статья видима'),
        ),
    ]
