# Generated by Django 3.1.4 on 2020-12-20 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201220_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='BlogPost_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='BlogPost_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='BlogPost_published',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 15, 56, 50, 913689, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
