# Generated by Django 3.1.4 on 2021-01-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210104_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name_plural': 'Серии'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name'], 'verbose_name_plural': 'Темы'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_modified',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_published',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_series',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_topic',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_visible',
            new_name='visible',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_slug',
            new_name='slug',
        ),
    ]
