# Generated by Django 3.2.5 on 2021-08-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210805_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(blank=True, to='blog.Topic'),
        ),
    ]
