# Generated by Django 3.2.5 on 2021-08-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210806_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='visible',
            new_name='public',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='visible',
            new_name='public',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='visible',
            new_name='public',
        ),
    ]
