# Generated by Django 3.1.4 on 2020-12-20 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201220_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 15, 58, 6, 169138, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
