# Generated by Django 3.1.4 on 2020-12-20 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201220_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('photo', 'Фотография'), ('travel', 'Путешествия'), ('books', 'Книги'), ('movies', 'Кино'), ('games', 'Игры'), ('development', 'Разработка'), ('ML', 'Машинное обучение'), ('finance', 'Финансы'), ('investment', 'Инвестиции')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 17, 52, 31, 465860, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='themes',
            field=models.ManyToManyField(to='blog.Theme'),
        ),
    ]
