# Generated by Django 3.1.4 on 2020-12-20 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201220_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 17, 54, 11, 706133, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
