# Generated by Django 3.2.5 on 2021-08-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210807_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
