# Generated by Django 3.1.4 on 2020-12-20 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201220_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 17, 55, 11, 408835, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='themes',
            field=models.ManyToManyField(blank=True, to='blog.Theme'),
        ),
    ]
