# Generated by Django 3.1.4 on 2020-12-20 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201220_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 18, 19, 37, 215863, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='themes',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='themes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('photo', 'Фотография'), ('travel', 'Путешествия'), ('books', 'Книги'), ('movies', 'Кино'), ('games', 'Игры'), ('development', 'Разработка'), ('ML', 'Машинное обучение'), ('finance', 'Финансы'), ('investment', 'Инвестиции')], max_length=65),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
