# Generated by Django 3.1.4 on 2020-12-20 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201220_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 18, 19, 47, 568199, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
