# Generated by Django 4.0 on 2022-04-14 20:38

import apps.scripts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cron', models.CharField(blank=True, max_length=255, validators=[apps.scripts.models.Job.cron_validator], verbose_name='Крон-выражение')),
                ('schedule', models.CharField(blank=True, max_length=255, verbose_name='Расписание')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('scheduled', models.BooleanField(default=False, verbose_name='Автоматический')),
                ('manual', models.BooleanField(default=False, verbose_name='Ручной')),
                ('slug', models.SlugField(blank=True, verbose_name='Слаг для запуска')),
            ],
            options={
                'verbose_name': 'Скрипт',
                'verbose_name_plural': 'Скрипты',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Время запуска')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Выполняется'), (1, 'Завершено')], null=True, verbose_name='Статус')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('success', models.BooleanField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='Успешный')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scripts.job')),
            ],
            options={
                'verbose_name': 'Выполнение',
                'verbose_name_plural': 'Выполнения',
                'ordering': ['-start'],
            },
        ),
    ]
