# Generated by Django 3.2.5 on 2021-07-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('schedule', models.CharField(blank=True, max_length=255, verbose_name='Расписание')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрытый')),
                ('command', models.URLField(blank=True, verbose_name='Запуск')),
            ],
            options={
                'verbose_name': 'Скрипт',
                'verbose_name_plural': 'Скрипты',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Время запуска')),
                ('status', models.IntegerField(choices=[(0, 'Выполняется'), (1, 'Завершено')], default=0, verbose_name='Статус')),
                ('end', models.DateTimeField(blank=True, verbose_name='Время завершения')),
                ('success', models.BooleanField(blank=True, verbose_name='Успешный')),
                ('result', models.TextField(verbose_name='Результат')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.script')),
            ],
            options={
                'verbose_name': 'Запуск',
                'verbose_name_plural': 'Запуски',
            },
        ),
    ]
