# Generated by Django 3.2.5 on 2021-07-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='hidden',
        ),
        migrations.AlterField(
            model_name='run',
            name='result',
            field=models.TextField(blank=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='script',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
