# Generated by Django 3.2.5 on 2021-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20210704_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='log',
            field=models.TextField(blank=True, verbose_name='Журнал'),
        ),
    ]
