# Generated by Django 3.2.5 on 2021-07-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_run_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.IntegerField(choices=[(0, 'Выполняется'), (1, 'Завершено')], verbose_name='Статус'),
        ),
    ]
