# Generated by Django 3.2.5 on 2021-07-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_alter_run_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scripts.script'),
        ),
    ]
