# Generated by Django 3.2.5 on 2021-07-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_alter_run_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='command',
        ),
        migrations.AddField(
            model_name='script',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Команда для запуска'),
        ),
    ]
