# Generated by Django 3.2.5 on 2021-07-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_auto_20210718_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='command',
            field=models.URLField(blank=True, verbose_name='Полный путь для запуска'),
        ),
        migrations.AlterField(
            model_name='script',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Слаг для запуска'),
        ),
    ]
