# Generated by Django 3.2.5 on 2021-08-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_auto_20210803_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['-start'], 'verbose_name': 'Выполнение', 'verbose_name_plural': 'Выполнения'},
        ),
    ]
