# Generated by Django 4.2.1 on 2023-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(max_length=255, upload_to="gallery/photos/", verbose_name="Изображение"),
        ),
    ]
