# Generated by Django 4.2.4 on 2023-09-21 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_alter_album_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Альбом",
                "verbose_name_plural": "Альбомы",
            },
        ),
        migrations.RenameField(
            model_name="album",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="album",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="photo",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="photo",
            old_name="uploaded",
            new_name="uploaded_at",
        ),
    ]
