# Generated by Django 4.2.6 on 2023-10-31 09:35

from django.db import migrations, models


def reorder_albums(apps, schema_editor):
    Album = apps.get_model("gallery", "Album")
    for order, item in enumerate(Album.objects.all(), 1):
        item.order = order
        item.save(update_fields=["order"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "gallery",
            "0004_alter_album_options_rename_created_album_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={
                "ordering": ["-order"],
                "verbose_name": "Альбом",
                "verbose_name_plural": "Альбомы",
            },
        ),
        migrations.AddField(
            model_name="album",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.RunPython(reorder_albums, reverse_code=migrations.RunPython.noop),
    ]
