# Generated by Django 4.2.7 on 2023-11-03 17:27

from pathlib import Path

from django.db import migrations, models

import gallery.utils
import personal_website.storages
from gallery.apps import GalleryConfig
from gallery.utils import move_photo_image, photo_image_upload_path


def update_image_paths(apps, schema_editor):
    """
    Пересохранить адреса изображений в соответствии с новой бизнес-логикой.
    """
    app_name = GalleryConfig.name
    Photo: models.Model = apps.get_model(app_name, "Photo")
    all_photos = Photo.objects.all()
    for photo in all_photos:
        old_path = photo.image.path
        new_path = move_photo_image(photo, old_path)
        file_name = Path(new_path).name
        new_relative_path = photo_image_upload_path(photo, file_name)
        photo.image = new_relative_path
        photo.save()


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_alter_album_options_album_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                max_length=255,
                storage=personal_website.storages.select_storage,
                upload_to=gallery.utils.photo_image_upload_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.RunPython(update_image_paths),
    ]
