# Generated by Django 5.0.1 on 2024-10-13 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0006_alter_photo_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ("-order",), "verbose_name": "Альбом", "verbose_name_plural": "Альбомы"},
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ("pk",), "verbose_name": "Фотография", "verbose_name_plural": "Фотографии"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("slug",), "verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
    ]
