# Generated by Django 6.0.2 on 2026-02-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_alter_album_options_alter_photo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="album",
            field=models.ForeignKey(
                help_text="Альбом, в котором размещена фотография",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="gallery.album",
                verbose_name="Альбом",
            ),
        ),
    ]
