# Опубликовать образ контейнера основного сервиса в несколько реестров:
# - GitHub Container registry
# - Docker Hub
name: Publish Docker image

# Выполняется после того, как закрыт Pull Request в ветку "main",
# если изменения в файлах не касаются только путей из перечня исключений.
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - 'nginx/**'
      - '.vscode/**'
  workflow_dispatch:

env:
  TEST_TAG: test-latest
  RELEASE_TAG: latest
  TEST_IMAGE_NAME: ghcr.io/${{ github.repository }}:${TEST_TAG}
  GITHUB_RELEASE_IMAGE_NAME: ghcr.io/${{ github.repository }}:${RELEASE_TAG}
  DOCKER_RELEASE_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/personal-website:${{ env.RELEASE_TAG }}

jobs:

  retag_and_push_image:
    # Запускается только если PR был смержен или workflow запущен вручную.
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Retag and push tested Docker image to Docker Hub and GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Получение тестового образа из GHCR
      - name: Pull test image from GHCR
        run: |
          docker pull ${{ env.TEST_IMAGE_NAME }}

      # Перетегирование тестового образа как "latest" для GHCR
      - name: Tag image as latest for GHCR
        run: |
          docker tag ${{ env.TEST_IMAGE_NAME }} ${{ env.GITHUB_RELEASE_IMAGE_NAME }}

      # Перетегирование тестового образа для Docker Hub
      - name: Tag image for Docker Hub
        run: |
          docker tag ${{ env.TEST_IMAGE_NAME }} ${{ env.DOCKER_RELEASE_IMAGE_NAME }}

      # Публикация образа с тегом "latest" в GHCR
      - name: Push image to GHCR with latest tag
        run: |
          docker push ${{ env.GITHUB_RELEASE_IMAGE_NAME }}

      # Публикация образа в Docker Hub
      - name: Push image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_RELEASE_IMAGE_NAME }}

  delete-test-tag:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: retag_and_push_image
    permissions:
      packages: write
    steps:
      - name: Instal GitHub CLI
        uses: actions/setup-gh-release@v1

      - name: Log in to GitHub CLI
        run: gh auth login --github-token ${{ secrets.GHCR_DELETE_TOKEN }}

      - name: Delete test tag from GitHub Container Registry
        run: |
          gh api -X DELETE /orgs/${{ github.repository_owner }}/packages/container/${{ github.repository }}/versions \
            --input <(echo -n '{"container_tags":["'"${{ env.TEST_TAG }}"'"]}')
