# Опубликовать образ контейнера основного сервиса в несколько реестров:
# - GitHub Container registry
# - Docker Hub
name: Release image


on:
  # Выполняется после того, как закрыт Pull Request в ветку "main",
  # если изменения в файлах не касаются только путей из перечня исключений.
  pull_request:
    types:
      - closed
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "nginx/**"
      - ".vscode/**"
  # Может быть запущено вручную.
  workflow_dispatch:

env:
  TESTED_TAG: tested
  LATEST_TAG: latest
  TESTED_IMAGE_NAME: ghcr.io/${{ github.repository }}:${TESTED_TAG}
  GITHUB_RELEASE_IMAGE_NAME: ghcr.io/${{ github.repository }}:${LATEST_TAG}
  DOCKER_RELEASE_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${LATEST_TAG}

jobs:

  # Перетегировать протестированный образ и опубликовать его в Docker Hub и GHCR.
  retag_and_push_image:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Retag and push tested Docker image to Docker Hub and GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Получение тестового образа из GHCR
      - name: Pull test image from GitHub Container Registry
        run: |
          docker pull ${{ env.TESTED_IMAGE_NAME }}

      # Перетегирование тестового образа как "latest"
      - name: Tag image as latest
        run: |
          docker tag ${{ env.TESTED_IMAGE_NAME }} ${{ env.GITHUB_RELEASE_IMAGE_NAME }}
          docker tag ${{ env.TESTED_IMAGE_NAME }} ${{ env.DOCKER_RELEASE_IMAGE_NAME }}

      # Публикация образа с тегом "latest" в реестрах
      - name: Push image with latest tag
        run: |
          docker push ${{ env.GITHUB_RELEASE_IMAGE_NAME }}
          docker push ${{ env.DOCKER_RELEASE_IMAGE_NAME }}

      # Удаление старого тега из GHCR
      - name: Delete tested tag from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GHCR_DELETE_TOKEN }}
          delete-tags: ${{ env.TESTED_TAG }}
